---
kind: pipeline
name: lily kramel CI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    image: alk3p/archlinux:kernel-devel
    environment:
      KBUILD_BUILD_USER: builder
      KBUILD_BUILD_HOST: equinix-ci
    commands:
      - git clone https://github.com/kdrag0n/proton-clang /drone/build-tools/proton-clang --depth 1
      - git clone https://github.com/alk3p/build-scripts /drone/build-tools/build-scripts --branch lemonade-r --depth 1
      - git clone https://github.com/alk3p/anykernel3 /drone/build-tools/anykernel --branch lemonade-r --depth 1
      - cd /drone/src
      - bash ../build-tools/build-scripts/build.sh upload
